#+LATEX_HEADER: \input{org-template.tex}
#+TITLE: Erstellung eines Relationalen Modells
#+AUTHOR: Lukas Wais
#+Language: de
#+OPTIONS: num:nil date:today toc:nil

Wir haben folgenden Ausgangspunkt:
Ein Buch was von einem Autor geschrieben wurde und einer Kategorie zugeordnet ist.

** Schritt 1: Identifizierung der Identitäten
- Buch
- Autor
- Kategorie

** Schritt 2: Identifizierung der Attribute
- Buch: ISBN, Titel, Jahr
- Autor: AutorID, Name, Geburtsdatum
- Kategorie: KategorieID, Name

** Schritt 3: Identifizierung der Beziehungen
- Buch-Autor-Beziehung: Ein Buch wird von einem Autor geschrieben \rarr 1:1 Beziehung.
- Buch-Kategorie-Beziehung: Ein Buch wird einer Kategorie zugeordnet \rarr 1:1 Beziehung.

** Schritt 4: Konvertierung der Entitäten und Attribute
- Buch(ISBN, Titel, Jahr)
- Autor(AutorID, Name, Geburtsdatum)
- Kategorie(KategorieID, Name)

** Schritt 5: Hinzufügen der Primärschlüssel 
- Buch( _ISBN_, Titel, Jahr)
- Autor( _AutorID_, Name, Geburtsdatum)
- Kategorie( _KategorieID_, Name)

** Schritt 6: Überführung des Beziehungstyps
Wir haben eine jeweils 1:1 Beziehungen und fügen deshalb zur Entität Buch, die Fremdschhlüssel von Autor und Kategorie ein.
Resultierend bekommen wir:  Buch( _ISBN_, Titel, Jahr, \dotuline{AutorID}, \dotuline{KategorieID})

* Überführung der Beziehungstypen
Als Ausgangspunkt definieren wir zwei Entitätstypen $T$ und $S$.

- *1:1 Beziehung:* einer der beiden Relationen wird um den Fremdschlüssel der anderen Relation erweitert.

- *1:N Beziehung:* es wird die Kardinalität eingehende Relation $T$ (eine) um den Fremdschlüssel der Relation $S$ (viele) erweitert.
  Beispiel: Ein Autor schreibt mehrere Bücher und ein Buch wird von einem Autor geschrieben \rarr Buch(..., \dotuline{AutorID}).

- *N:M Beziehung:* wir erstellen hier eine neue Relation $R=\{a_1, a_2, \ldots a_n \} \cup \{k_T\} \cup \{k_S\}$. Wobei $\{a_1, a_2, \ldots\}$ die Attribute der Beziehung sind
  und $k_T, k_S$ die Primärschlüssel von S und T sind.
  Nicht mathematisch ausgedrückt erstellen wir eine Verknüpfungstabelle. Beispiel ein Studenten besuchen mehrere Kurse. \\
  Student( _Martikelnummer_, Name),  Kurs( _ID_, Name) \\
  \rarr Verknüpfungstabelle(\dotuline{Matrikelnummer}, \dotuline{ID}) 

